[package]
name = "engine"
version = "0.1.0"
authors = ["Angelos Gkountis <agelosbb@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra-glm = "0.5.0"
bitflags = "1.0.4"
image = "0.22.3"
gli-rs = "0.3.1"
crossbeam-channel = "0.4"
assimp = "0.3.1"
gl_bindings = {path = "gl_bindings"}

[dependencies.glfw]
version = "0.34.0"
default-features = false

[target.'cfg(target_os = "unix")'.dependencies.glfw]
version = "0.34.0"
