[package]
name = "gl_bindings"
version = "0.1.0"
build = "build.rs"
authors = ["Angelos Gkountis <angelos.gkountis@gmail.com>"]
edition = "2018"

[lib]
name = "gl_bindings"
path = "src/lib.rs"

[build-dependencies]
gl_generator = "^0.14.0"
