name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev cmake libglfw3-dev
      - name: Build
        run: cargo build --all --verbose